### ISSUE TITLE
Label duplication

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/github-bot#136] opened 2017-04-13 08:09 UTC
If a collaborator adds labels before PR creation, the bot may add the same labels after creation. This is a harmless no-op, but duplicate log messages increase noise in the conversation.

Example: https://github.com/nodejs/node/pull/12381 (see two initial label comments).

Maybe a check for duplication can be added.

**Comment by phillipj** [comment] 2017-05-06 17:33
Closing this for now as it's a duplicate of https://github.com/nodejs/github-bot/issues/75. I have just contacted GitHub support about this, as it would have been best if we can avoid double checking what labels already exists **before** adding labels.

**Closed by phillipj** 2017-05-06 17:33 UTC
