### ISSUE TITLE
Wrong inline ARM Jenkins status on node PRs

### ISSUE THREAD

**Issue by phillipj** [nodejs/github-bot#108] opened 2016-12-19 21:04 UTC
There seems to be something fishy with the inline PR statuses forwarded from Jenkins. Looking at a few PRs which seem to have the same issue, it may be isolated to ARM builds.

These three PRs has inline ARM failure but Jenkins says they're green:

- https://github.com/nodejs/node/pull/6601: https://ci.nodejs.org/job/node-test-commit-arm/6587/
- https://github.com/nodejs/node/pull/10330: https://ci.nodejs.org/job/node-test-commit-arm/6613/
- https://github.com/nodejs/node/pull/10342: https://ci.nodejs.org/job/node-test-commit-arm/6622/

@jbergstroem you see anything suspicious with how the ARM builds are configured by any chance?

**Comment by phillipj** [comment] 2016-12-19 21:16
Seeing this in the logs related to PR 10342 and ARM:

```bash
19:05:25.868Z  INFO bot: Jenkins / Github PR status updated (req_id=d37fa1da-7246-4b88-bb8e-759d9d14be56, pr=10342, job=test/arm-fanned, status=pending)
19:05:38.608Z  INFO bot: Jenkins / Github PR status updated (req_id=f5b4cc52-097c-4026-a6aa-406bf0531197, pr=10342, job=test/arm, status=pending)
19:05:49.808Z  INFO bot: Jenkins / Github PR status updated (req_id=fbd97ff0-81a9-4d6e-91d4-a9519a490b66, pr=10342, job=test/arm, status=pending)
19:05:55.256Z  INFO bot: Jenkins / Github PR status updated (req_id=ab6678d5-2c40-4743-a1da-6cacb646f8a4, pr=10342, job=test/arm, status=pending)
19:30:23.187Z  INFO bot: Jenkins / Github PR status updated (req_id=5bd9d410-b387-422f-87ec-650a37982605, pr=10342, job=test/arm-fanned, status=success)
19:43:45.646Z  INFO bot: Jenkins / Github PR status updated (req_id=d97e6bfd-d6f8-44ad-bdca-981fa8f545aa, pr=10342, job=test/arm, status=success)
19:43:45.790Z  INFO bot: Jenkins / Github PR status updated (req_id=efead0d0-1155-4327-83fe-db966500ac3b, pr=10342, job=test/arm, status=failure)
```

From the looks of that, it's Jenkins pushing a failure status.

**Comment by jbergstroem** [comment] 2016-12-20 13:21
I've done some changes to both arm-fanned and arm. I think it might be related to the matrix type of job *holds thumbs*.

**Comment by phillipj** [comment] 2016-12-29 21:18
@jbergstroem to clearify, you did some changes supposed to fix these issues? Or had you done some changes previously which might have caused this issues in the first place?

Still seeing this in new PRs: https://github.com/nodejs/node/pull/10524 which says https://ci.nodejs.org/job/node-test-commit-arm/6788/ failed when it didn't.

**Comment by gibfahn** [comment] 2016-12-30 11:08
Related: https://github.com/nodejs/build/issues/572

**Comment by jbergstroem** [comment] 2016-12-30 11:35
The changes I did definitely didn't make things worse, but the issue still persists :(

**Comment by phillipj** [comment] 2017-01-28 11:16
Any updates here? Kinda sad to see this happening for most PRs, I assume it adds some doubts about whether or not these statuses are correct at all..

**Comment by jbergstroem** [comment] 2017-01-28 17:59
I've looked several times. Can't find whats wrong. Happy to share access but I think you already have it?

**Comment by phillipj** [comment] 2017-01-29 19:18
@jbergstroem I'd expect a "Configure"-link or something similar in the menu to the left if I had access?

<img width="757" alt="screen shot 2017-01-29 at 20 16 24" src="https://cloud.githubusercontent.com/assets/1231635/22407097/0bfac960-e660-11e6-9821-e4abb48889da.png">

**Comment by gibfahn** [comment] 2017-01-29 21:02
It's only people in [@nodejs/jenkins-admins](https://github.com/orgs/nodejs/teams/jenkins-admins) who can see it right?

**Comment by Trott** [comment] 2017-02-08 23:28
Is anyone actively working on this? Seems to have become one of those perma-ignore things for a lot of people in the main repo, which isn't healthy... :-(  Not even sure who to loop in... @nodejs/build maybe? @Fishrock123 maybe?

**Comment by gibfahn** [comment] 2017-02-09 01:34
cc/ @nodejs/jenkins-admins

**Comment by phillipj** [comment] 2017-04-14 19:38
Have to admint I haven't remembered to look into this I'm afraid. But by looking at the latest PRs and their inline status, it might look like failing ARM builds aren't as frequent anymore. @Trott would you agree?

**Comment by gibfahn** [comment] 2017-04-14 22:58
I *think* someone went in and fixed the ARM reporting, I want to say it was @joaocgreis but I could well be misremembering.

**Comment by jbergstroem** [comment] 2017-04-14 23:14
Have a faint memory @joaocgreis fixed it as well.

**Comment by Trott** [comment] 2017-04-14 23:48
>  @Trott would you agree?

Honestly, I haven't been paying attention to it! Will try to do so over the next few hours/days.

**Comment by joaocgreis** [comment] 2017-04-17 15:20
I fixed this. This issue looks like a duplicate of https://github.com/nodejs/build/issues/572. I don't have permissions, but I think this can be closed now.

**Comment by jbergstroem** [comment] 2017-04-17 17:45
Closing per @joaocgreis comment.

**Closed by jbergstroem** 2017-04-17 17:45 UTC
Labels: bug
